# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
