north:
  貫索星: |
    • 生涯をかけて、もう一人の自分と向き合い、距離を縮める作業を繰り返す。
    • 自分の世界を守り抜く不動の意志力を作り上げることが完成形。
    • 何を捨てて何を残すか、取捨選択の中で自分との葛藤を乗り越える。
    • 自己を確立できれば確固たる世界を築くが、できなければ迷い続ける人生になる。
  石門星: |
    • 人間関係を学ぶことが人生の役割のひとつ。
    • 仲間を増やすのではなく、「人はひとりでは生きられない」という命題の本質を学ぶ。
    • 人生の経験を通して、仲間の概念を高めていく。
    • 晩年になるにつれ、その完成度に応じた大事な人間関係が現れる。
  鳳閣星: |
    • 主観を排し、物事をありのまま観察することができるようになる。
    • 対象を客観的に理解し、その実体に迫る能力が高まる。
    • 外からはわからない孤独感を抱えながら、達観した人生の達人となる。
    • 晩年には専門的な分野で極める立場になりやすい。
  調舒星: |
    • 個人的な感情表現が原点だが、自己の欲求や欲望を排除し、純粋な表現に至る。
    • 宗教的・芸術的・美的な表現力が磨かれる。
    • 晩年に向かうほど創造性が豊かになり、多くの人に影響を与える。
    • 個人的な共感を超えた普遍的な表現が完成する。
  禄存星: |
    • 若いうちは私心・私欲の愛情だが、徐々に相手本位の愛情へと成長する。
    • 恋愛や個人的な愛情を超え、人助けや奉仕を通じてスケールを広げていく。
    • 蓄積した財産や愛情を、他者へと還元することが自然になる。
    • 晩年にはカリスマ的存在となり、人々に影響を与える。
  司禄星: |
    • 取り込んできたものの内容ではなく、「どう取り込んできたか」を重視する。
    • 効率的な方法を探求し、How to を極めることが役割。
    • 知識や経験、資産運用のノウハウを蓄積し、それを後進に伝える。
    • 晩年には、蓄積したノウハウが指針として多くの人に役立つ。
  車騎星: |
    • 自分の意思とは関係なく、運命に翻弄されながら自己を削ぎ落していく。
    • 理由や目的を求めるほど空回りし、最終的に「理由なき行為」の意味を知る。
    • 「人のために生きる」ことが自然となり、自己を捧げる存在へと昇華する。
    • 晩年には鳥が空を飛ぶように、人のために尽くすことが当たり前になる。
  牽牛星: |
    • 小さなプライドや見栄が、やがて人間形成へと昇華する。
    • 自己意識からどこまで私心を削れるかがポイント。
    • 完成形は単なる精神的なものではなく、現実の社会生活の中で達成されるべきもの。
    • 晩年には、理想的な社会人としての完成形に至る。
  龍高星: |
    • 自らの体験を通じて、関わった分野に変革をもたらすことが使命。
    • 試行錯誤と探究心の果てにのみ、真の完成がある。
    • 安易なひらめきや小手先の方法論ではなく、本質的な改革を目指す。
    • 晩年には、先駆者・開発者として後世に影響を残す存在となる。
  玉堂星: |
    • 知恵や学問、ノウハウを、主観を交えずに伝えることが使命。
    • 主観の完成度が伝承の完成度を決める。
    • 客観的に耐えうる形で知識を蓄積し、体系化する。
    • 晩年には、それを披露する機会が訪れ、後世に残す役割を果たす。
east:
  貫索星: |
    • 距離をとる本能があり、無意識に他者との距離を作る。
    • 自分から距離を埋めようとせず、行動が慎重で決断に時間がかかる。
    • 自信のあることには態度をはっきりさせるが、未熟なうちは自己主張が強くなり衝突も。
    • 変化が苦手で、経験した仕事を継続するタイプ。
    • 独立や専門的な仕事に向くが、万能型サラリーマンには不向き。
  石門星: |
    • 社交的本能を持つが、主観的な人志向で好き嫌いがはっきりしている。
    • 社会の場では社交術を発揮するが、プライベートでは好き嫌いに影響される。
    • 人を自分のエリアに引き込む本能があり、社交的に見えても自分本位と見られることも。
    • 善悪の区別がつきにくく、若い頃は悪にも善にも染まりやすい。
    • 人と関わる仕事向き（営業、セールス、政治家、相談役など）。
  鳳閣星: |
    • バランスを取る本能があり、付かず離れずの距離感を保つ。
    • 表面的には穏やかで優しそうに見えるが、深入りはしない。
    • 冷静な判断力があり、中立を保つのが得意。
    • 仕事では楽しめるもの、経理・事務、広報・マスコミ向き。
    • 個人的に密接な関係を築くのは苦手で、同性ばかりの職場では付き合いが悪いと思われることも。
  調舒星: |
    • こだわる本能を持ち、感情が判断基準になるため個性的な視点を持つ。
    • 主観的な見方が強く、人間関係が狭くなりやすい。
    • 気持ちが入らない仕事は苦手で、細かい神経を使う職業向き。
    • 芸術・表現系の仕事に向いており、技芸の世界で才能を発揮しやすい。
  禄存星: |
    • サービス本能があり、外面の良さが際立つ。
    • 好き嫌いに左右されず、相手に応じたサービスができる。
    • 相手を褒めるのが得意で、自然と人をいい気分にさせる。
    • 恋愛では惚れっぽくなりやすいが、えり好みしない。
    • 人助けに向いた職業（福祉・カウンセリング・接客業）や、お金に関わる仕事も適性あり。
  司禄星: |
    • 集める本能があり、貯める・蓄えることに長ける。
    • 庶民的で実用性を重視し、地味で目立たないが堅実。
    • 目的達成のためにお金を貯めるが、使うべき時には惜しまず使う。
    • 地道な努力型で、一度準備が整えば大きく飛躍する。
    • 経理・事務・データ整理など、コツコツ型の仕事に向く。
  車騎星: |
    • 役立ちたい本能があり、個人的欲求ではなく周囲のために動く。
    • 反応が速く、問題を見つけるとすぐに解決しようとする。
    • 問題解決能力が高いが、平和な環境だと無理に問題を見つけることがある。
    • 人の意見を素直に聞くより、問題点を指摘する傾向が強い。
    • スポーツ・ゲーム・動きのある仕事向き。
  牽牛星: |
    • 「いい顔」を作る本能があり、自己形成意識が強い。
    • 見た目や社会的評価を意識し、努力家になる傾向。
    • 環境に応じて自分の評価を上げようとするが、無理をすると挫折しやすい。
    • ブランド志向があり、一流志向を持つ。
    • 秘書・管理職など、人の役に立つ仕事向き。
  龍高星: |
    • 模索する本能があり、外面は気にせず、自己探求を優先する。
    • 試行錯誤を繰り返しながら、目標が定まると強い忍耐力を発揮する。
    • 従うだけのサラリーマンには向かず、専門職や技術職向き。
    • 海外志向が強く、自由な環境でのびのびと活躍するタイプ。
    • 感情に流されず、人間関係は広がりにくいが、庶民性はある。
  玉堂星: |
    • 動きたくない本能があり、外面はやや暗く見える。
    • 若いうちから地味な雰囲気を持ち、活力が出にくい。
    • 学習本能はあるが、持続力はそれほど高くない。
    • 机上の仕事向きで、お金に関する知恵も発揮しやすい。
    • 上司や先生を意識し、目上の質によって成長が左右される
south:
  貫索星: |
    • 二重のフィルターを通して世界を厳選し、自己納得できないものは排除する。
    • 流行や常識に流されず、自己同一の世界を築く。
    • 引き入れたものは強固に守るが、それが呪縛となることも。
    • 南にあることで「縛り付けられるべきもの」に出会う暗示。
  石門星: |
    • 人と関わることが自然であり、自分の側に取り込もうとする。
    • 時代の流れにうまく乗れる。
    • 興味を持ったものを無意識に取り入れる（人とは限らない）。
    • しかし、人の世界は人に苦しむ世界でもあり、試行錯誤を繰り返す。
    • 自分と同じ色の人・世界を手にすることがバックグラウンドになる。
  鳳閣星: |
    • 自分が世界を映す鏡のような存在（主観を交えない）。
    • 「楽しい世界がそこにあること」が楽しいのであり、自分が楽しむことが目的ではない。
    • 客観的視点を持ち、冷静な観察力と批判力を発揮する。
    • ものごとを最も良い状態にするための思考を持つ。
  調舒星: |
    • 自己認識は、反射して戻ってくるもの（対象）によって完成する。
    • 対象（子供・愛する人・作品・言葉など）へのこだわりが自己へのこだわりとなる。
    • どこに自己を投影するかが人生を左右する。
    • 描かれた世界（人生）をどう作り上げるかが重要。
  禄存星: |
    • 南にあることで、愛情奉仕の精神が最も高まる。
    • 自分の感情ではなく、相手本位の愛情を提供する。
    • 相手の思いを自分の中に取り込み、理解し、最善の状態を作ろうとする。
    • 恋愛よりも、広く愛情奉仕を求める傾向。
    • 一度入り込むと、自分からは抜けられない（相手主体の世界）。
  司禄星: |
    • 目の前にあるものを自分の中に取り入れる本能がある。
    • 陰星なので、好みが優先される（異性なら恋愛、知識なら勤勉さ）。
    • 広がりは少なく、常識的な範囲内での取り入れ作業となる。
    • 人を取り入れられないと混乱し、目の前の世界が崩れることも。
  車騎星: |
    • 禄存星のようなポジティブな愛情奉仕ではなく、条件反射的に人を助ける。
    • 考える余地がない使命感で動く（例：目の前に溺れている人がいたら助ける）。
    • 仕事では、私心なく純粋に役割をこなす世界。
    • 意図的・主体的ではなく、必要とされる場所に現れる。
  牽牛星: |
    • 自分を高めるもの（制服＝象徴）と出会い、それを着こなそうとする。
    • 出会ったものに努力を捧げることで自己を確立する。
    • 恋愛なら結婚へ、名誉や地位なら上昇、福祉や奉仕なら人徳を積む。
    • 問題を制服に転嫁するのではなく、自分がそれに見合う人間になる必要がある。
  龍高星: |
    • 客観的な入力ラインであり、単に言われたことを学ぶのではなく、本質を探る。
    • 常識的な世界ではなく、特殊な世界・専門分野に接する。
    • 哲学・宗教・芸術など、無形の世界がフィールド。
    • 懐疑的であり、簡単に人と同調しない（孤独だが寂しさは感じない）。
    • 人の力を借りずに、自分の道を突き進む。
  玉堂星: |
    • 入力装置が強く働き、言われたことを貪欲に吸収する。
    • 学ぶべき環境（親・学校・指導者）に出会うことが多い。
    • 環境の影響を受けるが、学習行為は続く。
    • 論理的・理屈屋になりやすく、精神性や創造力も高まる。
west:
  貫索星: |
    • 自分が環境を守る立場になることが多い。
    • 家庭環境と妥協せず、自然に距離を置きながらも連帯を模索する。
    • 親兄弟との距離を縮めるために葛藤や争いが生じやすい。
    • 結婚後も、配偶者を頼るより自分が家庭を守る立場になりやすい。
    • 自己同一現象（自分の価値観の維持）が途切れると、環境をあっさり捨てることも。
    • 経験値が増すと頑固さとプライドが強まり、傷つけられると爆発する。
  石門星: |
    • 家庭が前提で孤独な生活はなし。
    • 一人暮らしでもグループ活動や組織に属する。
    • 人を巻き込んで環境を作り、家族や組織をまとめる力がある。
    • 友達家族志向で、縦の親子関係や夫婦関係を作りにくい。
    • 共働き型の夫婦が理想で、分業的な役割分担を嫌う。
    • 政治力が加わり、単なる和合性を超えた大きなスケールを持つ。
  鳳閣星: |
    • バランス感覚に優れ、家庭内で冷静な観察をする。
    • 無意識の計算能力で、自分の立ち位置を決める。
    • 感情より合理性を重視し、結婚も感情だけでは決めない。
    • 問題処理能力が高く、無理のない状態を作り出すのが得意。
    • 必要以上のことをしない合理主義者で、怠け者に見られることも。
    • モノや遊びで生活の足りない部分を補う能力がある。
  調舒星: |
    • 細かいことに気が付き、家庭内評論家のような立場になりがち。
    • 生家では不平不満が多くなる（理解ある家族ならこの星は西にこない）。
    • 主観的な気遣いをするが、相手の望みと一致しないことがある。
    • 結果にこだわり、迷いや後悔がつきまとう。
    • 語ることで安心する傾向があり、結婚後も会話が重要。
    • 満たされないと一人を選びやすい。
    • 晩年は「悟る人」になるか、苦しむ孤独に陥るかの二択。
  禄存星: |
    • 愛情やお金を引き寄せるが、家庭には向きにくい（陽星は小さな場所には不向き）。
    • 個別的な愛情ではなく、スケールの大きな愛情を発揮する（調舒星があれば家族に集中）。
    • 客観的な奉仕精神を持ち、家族や配偶者のために大金を使うことも。
    • 経験値が増すと、相手に負担をかけない気遣いを身につける。
    • 家族のために黙って行動するタイプ（不言実行）。
    • 結婚には必ずしも向かず、家庭よりも広い範囲での愛情を持つ。
  司禄星: |
    • 家庭経済の星であり、家庭にあると一番活かしやすい。
    • 経験を活かし、過去から学んで準備を怠らない。
    • 地震などの体験から防災対策に力を入れるなど、備えることが習慣化。
    • 貯蓄や経験だけでなく、知識やスキルの蓄積にも優れる。
    • 整理整頓や分類が得意で、必要な時に適切なものを提示できる。
    • 地味で派手さはないが、頼りにされる存在。
    • 家庭を剋す作用もあるため、家庭内の和合が崩れると不安定になりやすい。
  車騎星: |
    • 西（家庭）には向かず、安定した生活環境を得にくい。
    • 自分が周囲のために動く環境になると最適（例：配偶者が忙しい職業）。
    • 家庭が落ち着かず、問題の多い環境になりやすい。
    • 家庭のために戦う星だが、安定した家庭では家族と対立することも。
    • 人のために役立ちたい本能が強く、問題の多い家庭・配偶者を選びやすい。
    • 経験値が増すと「正しさ」の概念が入り、正義感を持って家族を導こうとする。
  牽牛星: |
    • 恥ずかしくない家庭を作ろうとし、品性を重んじる。
    • 愛があれば何もいらない的な結婚はしない。
    • 家の中が散らかっていると、片付けるより隠して体裁を保つ傾向。
    • 結婚相手を選ぶ際、何かひとつ自尊心を満たす条件を求める（地位・財力・外見など）。
    • 生家が名家なら自然に発揮されるが、そうでない場合は自分が家の復権を果たそうとする。
    • 経験を積むと、見栄にとらわれず、現実的なプライドを持つようになる。
  龍高星: |
    • 常識を疑い、本質を探る星なので、家庭向きではない。
    • 家族団欒よりも個々が自由でいられる環境を好む。
    • 生家にあれば、早い自立を望み、固定された家庭生活に耐えられない。
    • 夫婦関係や家族関係の拘束が強いと破綻しやすい。
    • 新しい形の家庭を作れる可能性がある（国際結婚・年の差婚など）。
    • 経験値が増すと、自由への悟りを持ち、目的のない旅や放浪精神を持つようになる。
  玉堂星: |
    • 活気のある家庭環境は想定されていない。
    • 親の愛情の入力ラインであり、親との関係が深い家庭で育つ。
    • その影響を子供に還元しようとする（教育熱心になることも）。
    • 知性や学習が重要な家庭になりやすい（知的な配偶者と結婚することも）。
    • 家庭を維持するために学びが必要になるケースもある（配偶者の仕事の手伝いなど）。
    • 経験値が増すと、生活の知恵として学びを活かす。
    • 実用的な知識やノウハウを積み重ね、家庭の中で役立てる。
center:
  貫索星: |
    • 心の中にもう一人の自分がいて、環境を二重チェックする習性がある。
    • 自分との対話によって心が作られるため、外からの意見に流されにくい。
    • 兄姉がいる場合、その情報は確認前に容認することもある。
    • 環境による影響を大きく受け、穏やかな環境では成長が遅れ、変化の多い環境では認識が早まる。
    • 頑固な一面を持ち、方向転換が苦手。
  石門星: |
    • 和合する本性と、人を取り込む性質から、子供時代はお人よしになりがち。
    • 初期環境では単独行動に自信がなく、常に身近な人と手をつなごうとする。
    • 人と関わるために発揮する社交術が本音とは一致しないことが多い。
    • 家族の影響を強く受け、大人になってもその影響が続く。
    • 人間関係の試行錯誤を経て、真の社交術を身につけることで成長する。
  鳳閣星: |
    • 目の前の現実がすべてであり、過去や未来をあまり気にしない。
    • 余計な心配や後悔をしないため、穏やかな性格になる。
    • 子供時代はのんびりしているように見えるが、無意識に外の世界を観察している。
    • 環境や人の本質を客観的に見抜く力を持つ。
    • 両親の影響を大きく受けるが、情的な影響より社会的な行動を重視する。
    • 冷静な心を持ち、情に流されにくい。
  調舒星: |
    • 外部に向けて電波を発し、その反応を受けて認識する特性がある。
    • 子供時代は情報の整理ができず、自己都合の良い解釈だけを選択する。
    • 周囲からは常識を超えた、論理性のない考え方をするように見える。
    • 理解されない苛立ちが反抗心になり、孤立しやすい。
    • 内面的な発酵が芸術表現に発展することもあるが、ヒステリックな爆発に繋がることも。
    • 善悪・良否などの単純な価値観で自分を納得させながら成長する。
  禄存星: |
    • 自分の作った料理（愛情）を他者に食べてもらいたい欲求が強い。
    • 幼少期から肉親愛や兄弟愛が強く、保護者的な意識が芽生えやすい。
    • 自分を認めてくれる存在には深い情を持つが、敵には極端に冷淡。
    • ワンマンな性質があり、抜きん出たい想念を持つ。
    • 一方的に感情を押し付けることがあるが、愛情を受け止めてもらうことで成長する。
    • 愛情を裏切られると、愛情に執着する偏った心になる可能性がある。
  司禄星: |
    • 欲しいものを手に入れることが心の成長につながる。
    • 幼少期は周囲から評価されることや、何かをもらうことを期待する。
    • 手に入らないと苛立ち、手に入りすぎると感謝を忘れ努力しなくなる。
    • 努力して得ることの重要性を学ぶことで心が成長する。
    • 第二ステップとして、評価されるために努力することを覚える。
    • 人に尽くすことを学ぶと、努力の結果が自分の糧になることを理解する。
  車騎星: |
    • 自分の意思とは関係なく、使命に向かって突き進む本能がある。
    • 相手が求めるものを直感的に察知し、それを与えようとする。
    • 親・仲間・社会のために自分を犠牲にしやすい。
    • 幼少期はスポーツや勝ち負けのあるゲームに熱中し、負けず嫌いの性質を強める。
    • 危険な選択肢を選びやすく、リスクの高い状況に飛び込むことが多い。
    • 方向が定まると、生涯をかけて社会や人々のために戦うような精神を持つ。
  牽牛星: |
    • 目的を達成するための試行錯誤を繰り返す。
    • 自分の問題として捉え、成功も失敗もすべて自分の責任と考える。
    • 親や先生に対して奉仕的に報いようとするが、冷静に達成手段を考える。
    • 一見見当違いに見える方向へ進むこともあるが、本人なりの解決策を模索している。
    • 試行錯誤の途中で正解を与えられると混乱し、目的を見失いやすい。
    • 経験を積むことで柔軟な思考を身につけ、理想の自分を作り上げる。
  龍高星: |
    • 「なぜ？」「どうして？」という疑問が思考の原点。
    • 誰かに教わるのではなく、自分で調べ、理解することで知識を得る。
    • 表面的な理解では満足せず、多角的に物事を観察し、本質を探る。
    • 考えをまとめるのに時間がかかり、話が回りくどくなることがある。
    • 子供時代は極端になりやすく、無口で行動的か、おしゃべりで大人びたタイプに分かれる。
    • 無目的に動く放浪性を持ち、環境の影響を強く受ける。
    • 現実か精神のどちらかで苦労する暗示があるが、それを乗り越えるとあらゆる世界に適応できる。
  玉堂星: |
    • 動くために食事をするように、知識を得るために頭を使う。
    • 幼少期は与えられた情報をそのまま記憶し、選別ができない。
    • 環境の影響を強く受け、良いものも悪いものも無分別に吸収する。
    • 知識が一定レベルに達するまで自己表現は控える。
    • 目の前の状況を論理的に解釈する能力が高い。
    • 失敗や間違いを恐れ、言い訳が得意だが、内面の弱さを認めると大きく成長する。
