north:
  equal: |
    主 = 北 準自然型
    • 目上との関係が対等であり、個人対個人の意識で接する。
    • 目上から見ると生意気に映るが、努力する姿勢が評価されることもある。
    • 精神的に目上を強く意識する。
    • 目上が小さいと傲慢に、大きすぎると反抗的になる傾向がある。
    • 強い親を持つと、親子ともに苦労が増す。
    • 人間的に成長すれば対等な関係を保てるようになる。
  generates: |
    主 → 北 不自然型
    • 目上を支える意識が強く、親孝行の関係になりやすい。
    • 目上にとらわれやすく、相手の性格や人生観に大きく影響を受ける。
    • 親や目上に尽くしすぎて自己犠牲に陥る可能性がある。
    • 自分の本質が「親を支えること」だと思い込む傾向がある。
    • 宿命的に合っていれば問題ないが、他の構造と矛盾すると葛藤が生じる。
    • 目上に従順であり、親離れが遅くなりがち。
  generated_by: |
    主 ← 北 不自然型
    • 上から恩恵を受けやすく、依存心や甘えが育ちやすい。
    • 親の業績や財を苦労せず受け継ぐこともある。
    • 受けすぎると運命に逆行し、本質から逸れる可能性がある。
    • 幼い頃は問題なく、順調な親子関係になりやすい。
    • 成人後も親に頼る傾向が強まり、自立心が育ちにくい。
    • 人間性は純粋で素朴になるが、精神的成長が遅れる。
    • 保護を受けることは問題ないが、依存しないよう自立心を養う必要がある。
  controls: |
    主 << 北 自然型
    • 自分が親や目上を剋す形であり、自分の立場を守りつつ成長できる。
    • 上から剋されたり、生じられたりする関係を好まない。
    • どんな環境でも自分本来の質が変わらない。
    • 親子関係では一般的な形。
    • 自助努力がすべてであり、親が環境を整えても本人の器が小さいと発展しない。
  controlled_by: |
    主 << 北 やや不自然型
    • 本来剋すべき相手（目上）に剋されるため、不自然さがある。
    • 社会的には親が子をしつけ、上司が部下を管理する形で自然。
    • 自己と相手の意識にズレが生じ、精神的な試練が多い。
    • 上からの厳格さを受け、自分も厳格な性質を持つようになる。
    • 上に尽くし、奉仕する傾向がある。
    • 形としては従いつつも、精神的には影響を受けず自立を目指すのが理想。
east:
  equal: |
    主 = 東 やや不自然型
    • 自分の気持ちを社会生活にそのまま反映したいという願望が強い。
    • 労働の対価（財産・名誉など）を求め、それが満足度の指標になる。
    • 他人と歩調を合わせるのは苦手で、ライバル心が強くなる傾向がある。
    • 単独行動向きであり、協調社会では孤立しやすい。
    • 自分を理解してくれる目上に出会うと飛躍的に成長できる。
  generates: |
    主 → 東 不自然型
    • 社会に対する奉仕の精神が強く、純粋で情に厚い。
    • 周囲に献身的になり、人望を集めるが、消耗も多い。
    • 人からの援助を受けながらも、自分の世界を創造する方向へ向かう。
    • 人生の道のりは波乱含みだが、試練を乗り越えるたびに成長できる。
    • 目的が早く定まれば大成功の可能性があるが、遅れると成功も遅くなる。
    • 同僚や友人の影響で人生が大きく変わることがある。
  generated_by: |
    主 ← 東 不自然型
    • 社会からの援助や保護を受ける立場になりやすい。
    • 受け入れる姿勢が強く、幅広い人間関係を築くことができる。
    • 努力すれば比較的スムーズに現実が展開するが、精神的満足は得にくい。
    • 望む結果が得られるとは限らず、常に不満がつのりやすい。
    • 恵まれているように見えても、現状に満足できず、変化を求める。
    • 周囲の助けを受けすぎることで方向を誤るリスクがある。
  controls: |
    主 >> 東 準自然型
    • 社会に対して強い意識を持ち、自分の存在をはっきり示したがる。
    • 仕事や人間関係でも自分のペースを貫こうとする。
    • 現実的な考え方をしつつも、未来に対する不安を抱えがち。
    • その不安を前進することで克服しようとし、強い推進力を持つ。
    • 精神的な安定をどこに求めるかが生涯の課題となる。
  controlled_by: |
    主 << 東 自然型
    • 堅実で現実的な生き方をし、社会との調和を重視する。
    • 良い人間関係を築き、争いを避ける傾向がある。
    • 急激な成功や大きな波乱は少なく、一歩ずつ着実に進む。
    • 受容の姿勢が基本で、単独よりも組織内で成果を出しやすい。
    • 社会生活の中で神の加護を受けるような形となる。

south:
  equal: |
    主 = 南 やや不自然型
    • 目下と対等な関係になり、仲間意識が芽生えやすい。
    • 縦の統率がとれなくなり、組織内での管理が難しくなることも。
    • 目下から歓迎されるが、軽く見られたり、反発されることもある。
    • 子供と友達のような関係になりやすく、精神的に若々しさを保つ。
    • 天才的なひらめきを発揮することがあり、創造性が豊か。
  generates: |
    主 → 南 準自然型
    • 目下のために尽くす姿勢が自然に根付く。
    • 目下に振り回されやすく、過保護・過干渉になりがち。
    • 自分を高めることで目下から押し上げられ、運気が上昇する。
    • 目下の数が多くなると、強運な人と弱運な人が極端に分かれる傾向がある。
    • 自分の成長次第で、良い目下との縁を引き寄せることができる。
  generated_by: |
    主 ← 南 自然型
    • 目下からの支えによって運気が上がるが、若年期は目下が少なく効果が薄い。
    • 社会的地位が上がる中年期以降に順調になりやすい。
    • 目下に対して厳しさと温和さを兼ね備える。
    • 自然と中心的な立場を取り、人間関係をまとめる力を持つ。
    • 目下に影響されやすいため、広範な行動力を意識することが重要。
  controls: |
    主 >> 南 不自然型
    • 目下に対して非常に厳しく、プレッシャーをかけやすい。
    • 反発されるとさらに抑えつけるワンマン傾向が出る。
    • 期待が大きすぎるがゆえに、目下に過度な試練を与えてしまう。
    • 目下が弱いと潰してしまい、自滅させるリスクがある。
    • 知性や人徳が備わっていれば、カリスマ的指導者になれる。
  controlled_by: |
    主 << 南 不自然型（中心が南に剋される形）
    • 目下からの干渉が強く、自分の本質を曲げられやすい。
    • 部下や子供を持つと苦労が増える。
    • 目下の要求を満たそうとしすぎて、自分を見失う可能性がある。
    • 強い目下を育てる環境が整わず、彼らの運を落とすこともある。
    • 試練を多く経験することで成長し、老年期には目下からの恩恵を受ける。
west:
  equal: |
    主 = 西 やや不自然型
    • 家庭や夫婦関係が対等になるため、喜びも争いも同格になりやすい。
    • 夫婦共通の目的があればうまくいくが、相反する要素があると衝突する。
    • 親や目上の兄弟からの批判を受けることがある。
    • 力量が近い相手とは安定しやすいが、差が大きいと不満や反発が生じる。
    • 仲間は多くても、親友を作りにくい傾向がある。
  generates: |
    主 → 西 自然型
    • 家庭が安住の場となり、家族を大切にする。
    • 家族に精神的な影響を与え、満足度の高い関係を築く。
    • 家族への愛情が強く、身内びいきの傾向がある。
    • 配偶者が弱いと良い関係を築けるが、強いとわがままを助長させる。
    • 波乱が少なく、安定した家庭を築きやすい。
  generated_by: |
    主 ← 西 準自然型
    • 家族から助けられ、支えられる関係性を持つ。
    • 家族を過大評価する傾向があるが、家庭の影響を強く受ける。
    • 家庭を自ら変えたり改革する力は弱い。
    • 内輪に恵まれ、社会でも補佐的な立場でサポートを受けやすい。
    • 過去の経験や行動を活かして、人生に活かすことができる。
  controls: |
    主 >> 西 不自然型
    • 家庭をコントロールしようとし、安住の場になりにくい。
    • 配偶者や家族の精神的負担が大きくなる。
    • 自分中心の家庭になり、家族の意見が反映されにくい。
    • 教養がないとワンマンになり、家族との距離が生じやすい。
    • 夫婦関係が一方通行になり、精神的な助け合いが少なくなる。
  controlled_by: |
    主 << 西 不自然型
    • 家庭からの影響が強く、自由にくつろげる環境になりにくい。
    • 結婚すると配偶者の影響を強く受け、多忙な生活になりがち。
    • 未来に対する不安が強く、計画的な生活を送るようになる。
    • 配偶者の運勢が強いことが多く、自分が弱いと消耗し、強いと対立しやすい。
    • ちょうどよいバランスの家庭を築くことが難しい。
