class CycleMapping < ActiveHash::Base
  # 異常干支の組み合わせ
  ABNORMALS = ['甲戌', '乙亥', '辛巳', '壬午', '丙戌', '丁亥', '戊子', '癸巳', '戊戌', '己亥', '庚子', '辛亥', '丁巳'].freeze

  self.data = [
    { id: 1, stem: '甲', branch: '子' },
    { id: 2, stem: '乙', branch: '丑' },
    { id: 3, stem: '丙', branch: '寅' },
    { id: 4, stem: '丁', branch: '卯' },
    { id: 5, stem: '戊', branch: '辰' },
    { id: 6, stem: '己', branch: '巳' },
    { id: 7, stem: '庚', branch: '午' },
    { id: 8, stem: '辛', branch: '未' },
    { id: 9, stem: '壬', branch: '申' },
    { id: 10, stem: '癸', branch: '酉' },
    { id: 11, stem: '甲', branch: '戌' },
    { id: 12, stem: '乙', branch: '亥' },
    { id: 13, stem: '丙', branch: '子' },
    { id: 14, stem: '丁', branch: '丑' },
    { id: 15, stem: '戊', branch: '寅' },
    { id: 16, stem: '己', branch: '卯' },
    { id: 17, stem: '庚', branch: '辰' },
    { id: 18, stem: '辛', branch: '巳' },
    { id: 19, stem: '壬', branch: '午' },
    { id: 20, stem: '癸', branch: '未' },
    { id: 21, stem: '甲', branch: '申' },
    { id: 22, stem: '乙', branch: '酉' },
    { id: 23, stem: '丙', branch: '戌' },
    { id: 24, stem: '丁', branch: '亥' },
    { id: 25, stem: '戊', branch: '子' },
    { id: 26, stem: '己', branch: '丑' },
    { id: 27, stem: '庚', branch: '寅' },
    { id: 28, stem: '辛', branch: '卯' },
    { id: 29, stem: '壬', branch: '辰' },
    { id: 30, stem: '癸', branch: '巳' },
    { id: 31, stem: '甲', branch: '午' },
    { id: 32, stem: '乙', branch: '未' },
    { id: 33, stem: '丙', branch: '申' },
    { id: 34, stem: '丁', branch: '酉' },
    { id: 35, stem: '戊', branch: '戌' },
    { id: 36, stem: '己', branch: '亥' },
    { id: 37, stem: '庚', branch: '子' },
    { id: 38, stem: '辛', branch: '丑' },
    { id: 39, stem: '壬', branch: '寅' },
    { id: 40, stem: '癸', branch: '卯' },
    { id: 41, stem: '甲', branch: '辰' },
    { id: 42, stem: '乙', branch: '巳' },
    { id: 43, stem: '丙', branch: '午' },
    { id: 44, stem: '丁', branch: '未' },
    { id: 45, stem: '戊', branch: '申' },
    { id: 46, stem: '己', branch: '酉' },
    { id: 47, stem: '庚', branch: '戌' },
    { id: 48, stem: '辛', branch: '亥' },
    { id: 49, stem: '壬', branch: '子' },
    { id: 50, stem: '癸', branch: '丑' },
    { id: 51, stem: '甲', branch: '寅' },
    { id: 52, stem: '乙', branch: '卯' },
    { id: 53, stem: '丙', branch: '辰' },
    { id: 54, stem: '丁', branch: '巳' },
    { id: 55, stem: '戊', branch: '午' },
    { id: 56, stem: '己', branch: '未' },
    { id: 57, stem: '庚', branch: '申' },
    { id: 58, stem: '辛', branch: '酉' },
    { id: 59, stem: '壬', branch: '戌' },
    { id: 60, stem: '癸', branch: '亥' }
  ].freeze
end
